- config/auditing.php
- src/AuditingServiceProvider.php
- src/Log.php
This PR allows the use of the configuration file for auditing.
````php
//Example:
return [
'model' => App\User::class,
];
```
> Added configuration file

- README.md
Put together some suggestions 'cuz I said I would :). Let me know what you think. We can add the differentiation between revisionable in the future as well. I didn't have any good ideas on that to suggest yet.
> Some suggestions on first part of readme

- src/AuditingTrait.php
Now app crashes when no attribute set
> Fix crash when create empty record (no attributes set)

- database/migrations/2016_05_22_190217_add_fields_to_log_table.php
- src/AuditingTrait.php
I have added a new migration for the extra fields and updated AuditingTrait to save them to log.
> Add fields for saving user's IP and current request route when logging.

- src/AuditingTrait.php
https://github.com/owen-it/laravel-auditing/issues/62
> Function get user id renamed

- src/AuditingTrait.php
Laravel events provides a simple observer implementation, which allows us to subscribe and listen to events in our application.
> [2.4] Support events added

- src/Log.php
@anteriovieira this fix the conflict.
> Allow custom names for owner_type.

- config/auditing.php
- src/CustomAuditMessage.php
Changed User model lookup from local configuration to use auth.providers.users.model provided from the Laravel framework.
Less configuration to do for the package - easier integration.
> Removed User model from configuration

- src/AuditingServiceProvider.php
This change fixes #149 for me.
The change should be compatible with Laravel 5x as well, although I haven't confirmed it.
> Fixing Lumen compatibility

- src/CustomAuditMessage.php
Show custom fields only when field has changed
#157
> [3.1] Show custom fields only when field has changed

- src/Console/stubs/audits.stub
> feat(*): change the user_id column type to unsignedInteger

- composer.json
> fix(composer): use correct branch-alias

- .travis.yml
- src/AuditingTrait.php
- added travis config from master and changed the versions for supported PHP to those defined on branch 3.1 (https://github.com/owen-it/laravel-auditing/blob/3.1/.travis.yml)
> 	Interrogate database for counting rows for deletion only if model has historyLimit attribute set

- src/Auditable.php
- src/Auditor.php
- src/Contracts/Auditable.php
- src/Contracts/UserResolver.php
- tests/AuditableTest.php
- tests/Stubs/UserResolverStub.php
Work done in this PR:
- Fix for #212 
- Fix for #213
> [4.0] Fixes

- src/Auditable.php
- src/Console/stubs/audits.stub
- src/Models/Audit.php
- tests/AuditModelTest.php
- tests/AuditableTest.php
- tests/Stubs/AuditableStub.php
Store the User Agent string on each `Audit`.
> User Agent string logging

- src/Auditable.php
> [Fix] Generate a standards compliant SQL query

- CHANGELOG.md
- src/Auditable.php
- src/Models/Audit.php
Latest fixes and code cleanups.
> Version 4.0.6

- .gitattributes
- .github/ISSUE_TEMPLATE.md
- CHANGELOG.md
- src/AuditableObserver.php
This pull request:
- Adds a GitHub issue template to the repository
- Fixes #233 properly
> [4.0.7] Fix #233 properly

- CHANGELOG.md
- composer.json
- src/Audit.php
- src/Console/stubs/audits.stub
Work done in this pull request:
- Added support for Laravel 5.5 auto-discovery
- Fix `Audit` **resolveData()** method (use `User` foreign key value)
> Updates and fixes

- src/Auditable.php
- tests/AuditableTest.php
Work done in this pull request:
- Fix `toAudit()` method by using the foreign user key defined in the configuration
- Update tests
> Auditable fixes

- CHANGELOG.md
- CONTRIBUTING.md
- src/Auditable.php
- tests/AuditableTest.php
- tests/Stubs/AuditableStub.php
Work done in this pull request:
- Added ability to define custom methods to handle audit events;
- Code cleanups;
> Version 4.1.4

- CHANGELOG.md
- drivers/driver.stub
- src/Auditable.php
- tests/Unit/AuditableTest.php
> [V5] Final

- src/Auditable.php
- src/Exceptions/AuditableTransitionException.php
- tests/Functional/AuditingTest.php
- tests/Models/Article.php
- tests/Unit/AuditableTest.php
- tests/database/factories/ArticleFactory.php
- tests/database/migrations/0000_00_00_000003_create_articles_table.php
This pull request brings some more changes, mainly to the `Auditable` trait. 
Some cleanups here and there, and an increase in the number of tests.
> [V5] Last minute stuff

- src/Auditable.php
- tests/Unit/AuditableTest.php
This pull request fixes a bug in the `transitionTo()` method and increases its test coverage.
> [V5] Fix transitionTo() method

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- composer.json
- src/Auditable.php
- tests/Unit/AuditableTest.php
> Version 5.0.2

- CHANGELOG.md
- src/AuditingServiceProvider.php
> [V5] Fix Lumen installation issue

- CHANGELOG.md
- README.md
> [V6] Final

- .scrutinizer.yml
Work done:
- Test the package against PHP 7.0, 7.1 and 7.2;
- Use the most recent static analysis engine;
> [FEAT] Tweak scrutinizer

- src/Audit.php
- src/Auditable.php
- src/AuditingServiceProvider.php
Work done:
- Minor code optimisations;
> Minor optimisations

- src/Auditable.php
- src/Facades/Auditor.php
Some more fixes before next release.
> Minor fixes

- database/migrations/audits.stub
- src/Auditable.php
- src/Drivers/Database.php
- tests/database/migrations/0000_00_00_000001_create_audits_test_table.php
Your readme stipulate that Laravel 5.2 is still supported with version 7.x
I found problem with 6.0 and 6.1 code where functions or features don't exist in Laravel 5.2
> Fix/support laravel 5.2

- src/Models/Audit.php
- tests/Unit/AuditableTest.php
> fix(AuditModel): cast auditable_id to integer

- src/Contracts/Audit.php
> fix(Audit): wrong method name in the interface

- .github/workflows/run-tests.yml
- .styleci.yml
- composer.json
- src/Audit.php
- src/AuditingServiceProvider.php
- src/Console/AuditDriverCommand.php
- src/Console/InstallCommand.php
- src/Models/Audit.php
- tests/AuditingTestCase.php
- tests/Functional/AuditingTest.php
- tests/Functional/CommandTest.php
- tests/Unit/AuditTest.php
- tests/Unit/AuditableTest.php
Adding a test config for github actions
> Add test-matrix for versions supported

- .styleci.yml
- src/Auditable.php
Rollup of issues and pr's for for minor
> 12.1.0 dev

- src/Audit.php
> Use date serialization from auditable

- src/Resolvers/UserResolver.php
Proposed changes from #704 
Included the condition update, but will "revert" in case you do not want it.
> fixed UserResolver (fixes #704)

- .github/workflows/run-tests.yml
> Actions v3 on tests

- src/Auditable.php
> Fix upgrading links

- src/Contracts/Auditable.php
This allows statistical analyzes tool (PHPStan + Larastan) to detect the relation
> Hint relation type for audits

- config/audit.php
Nothing important, just cleaning up the comment
> Removed User from comment

- src/Resolvers/IpAddressResolver.php
Reverts owen-it/laravel-auditing#743
Closes #804
**Info**: https://github.com/owen-it/laravel-auditing/issues/804#issuecomment-1472178550
> Revert "Update IpAddressResolver.php"

- composer.json
Use 'https' instead of  'http' for the homepage
> Use `https` for the homepage on the `composer.json` file

- src/Resolvers/UrlResolver.php
https://github.com/owen-it/laravel-auditing/issues/888
> Correct reference to Request facade

- tests/Unit/AuditTest.php
- tests/Unit/AuditableObserverTest.php
- tests/Unit/AuditableTest.php
These are incorrect and should be fixed. Not really a v14 specific thing so extracted the commit to preserve the author I hope.
> Correct Test Namespaces
