owen-it/laravel-auditing

- README.md
I made some changes at your documentation at installation sections and log messages.
> Review at documentation

- config/auditing.php
- src/AuditingTrait.php
Added some fixes for issue #49 .
Adds config option for logging console (eg. artisan db:seed) and also adds fix to return "console" as route when needed.
> Add config option to audit console or not. Fix for route bug if in console

- src/AuditingTrait.php
This update allows custom names for owner_type field by getting the morph class alias set by "Relation::morphMap()".
> Allows custom names for owner_type.

- src/Auditable.php
Response to https://github.com/owen-it/laravel-auditing/issues/106
Behaviour can be ignored by setting protected `$auditRespectsHidden = false;` on the model.
> [3.0] Audited values will respect $hidden/$visible

- composer.json
- config/auditing.php
- src/AuditQueuedModels.php
- src/Auditor.php
- src/AuditorManager.php
- src/Auditors/DatabaseAuditor.php
- src/Console/stubs/auditor.stub
- tests/AuditingQueuedAuditTest.php
This option allows you to control if the operations that audit your models with your auditors are queued. When this is set to "true" then all models  auditable will get queued for better performance.
```php
// config/auditing.php
'queue' => true,
```
Suggested by @Cannonb4ll  https://github.com/owen-it/laravel-auditing/issues/77
> [3.1] Queue Auditable Models

- src/Auditable.php
When you save a single model instance two times in the same session, then the second audit will also contain all the changes that have already been reflected in the first audit.
Example: Assume there is a user John Doe. Now we do:
```php
$u->firstname = 'Richard';
$u->save();
$u->lastname = 'Roe';
$u->save();
```
This generates two audits:
````php
{
old: '{"firstname":"John"}',
new: '{"firstname":"Richard"}'
}, {
old: '{"firstname":"John","lastname":"Doe"}',
new: '{"firstname":"Richard","lastname":"Roe"}'
}
````
This pull request ensures that the second audit only contains:
````php
{
old: '{"lastname":"Doe"}',
new: '{"lastname":"Roe"}'
}
````
Note that the [`syncOriginal()` function in `Illuminate\Database\Eloquent\Model`](https://github.com/laravel/framework/blob/v5.3.18/src/Illuminate/Da …
> Fix double audits when saving two times in same session

- config/audit.php
- src/Auditable.php
- src/Console/AuditDriverMakeCommand.php
- src/Console/AuditTableCommand.php
- src/Console/InstallCommand.php
- src/Models/Audit.php
In this PR:
- Make the exclusion logic for hidden/visible attributes behave as in version 3.x
- Allow `json_encode()` arguments to be passed via `getMetadata()` and `getModified()`
- Remove `getModifiedAttributes()` method
> [4.0] fix/auditable-exclusions

- src/Console/stubs/audits.stub
This allows us to change database driver configuration before calling "php artisan migrate".
> Fix migration stub to use configurations for database driver

- src/Console/stubs/driver.stub
Put back the `DummyNamespace` and `DummyClass` replacement string so that the  `AuditDriverMakeCommand` works as expected.
> Fix for issue #226

- src/Auditable.php
Setting a default sort order for the `audits()` relation method in the `Auditable` trait has been causing issues in a few RDBMS.
From now on, users who want to change the default sorting behaviour (`created_at` ASC), will have to do it themselves taking into account the RDBMS they're using.
> [FIX] Remove explicit sort from the audits relation

- src/Models/Audit.php
Possible fix for #206, not tested for side-effects, but seems to run OK with local dataset.
> Fix iterating over all audits, if audible model is not resolved

- CHANGELOG.md
- src/Audit.php
- src/Console/stubs/audits.stub
- src/Models/Audit.php
- tests/AuditModelTest.php
Work done in this pull request:
- Added the `updated_at` column to the `audits` table migration;
This also simplifies the `Audit` model implementation, which won't require the `$timestamps` and `$dates` attributes to be set anymore.
Don't forget to update your `audits` table, when upgrading!
> Audits updated_at

- src/Audit.php
I ran into an issue where if I modify an audited model without a user (ie. from the CLI) and then try and grab the audits it throws:
`PHP Fatal error:  Call to a member function attributesToArray() on null in [...]/vendor/owen-it/laravel-auditing/src/Models/Audit.php on line 128`
This modification ensures there is a user set before calling `$this->user->attributesToArray()` therefor avoiding the fatal error
> Ensure $this->user is not null

- src/Drivers/Database.php
Database driver still constructs static OwenIt\Auditing\Models\Audit class instead of using the configured Model class in 'audit.implementation' section of config file.  
This is required so I can override the Audit model and store Audit trail in Mongo database store using my own model implementation.
> Remove static reference to OwenIt\Auditing\Models\Audit in Database driver

- src/Auditable.php
- tests/AuditableTest.php
- tests/Stubs/AuditableStub.php
Auditable Events can now have `*` in their names and can define a custom attributes method.
> Update the Auditable Events definition

- CHANGELOG.md
- src/Auditable.php
- tests/Functional/AuditingTest.php
This PR adds the ability to quickly enable/disable auditing.
Fixes #387
> [FEAT] enable/disable auditing

- src/Resolvers/UserAgentResolver.php
> Replace userAgent method call - fixes incompatibilty with Illuminate 5.2

- CHANGELOG.md
- src/Audit.php
- tests/Unit/AuditTest.php
This pull request fixes an issue with the Tags feature (introduced in **v5.0.0**), when using the `getMetadata()` method in the `trans()` and `@lang()` helpers, which would cause an error (see #418).
The fix does cause a minor breaking change, although it's quite straightforward to mitigate (in case you're using the tag values).
Previous calls to `$audit->tags`, which would return an array (`['foo', 'bar',]` or `[]`), now return the original string value (`foo,bar` or `null`) as stored in the database.
To get the tags as an `array`, like in versions **v5.0.0** up to **v6.1.0**, you should now use the `getTags()` method instead: `$audit->getTags()`
> [FIX] Issue 418 - Audit presentation

- config/audit.php
- database/migrations/audits.stub
- src/Audit.php
- src/Auditable.php
- src/Contracts/Audit.php
- src/Resolvers/UserResolver.php
- tests/Unit/AuditTest.php
- tests/Unit/AuditableObserverTest.php
- tests/Unit/AuditableTest.php
- tests/database/factories/AuditFactory.php
- tests/database/migrations/0000_00_00_000001_create_audits_test_table.php
The code in this pull request is based on #420 but with a few simplifications.
**Work done:**
Special thanks to [Webparking](https://github.com/Webparking) for their initial work!
@crashkonijn & @remkobrenters
> [FEAT] V7 - Multi user audits

- src/Audit.php
- src/Models/Audit.php
This PR moves the Auditable/User morph relations from the trait to the model, making it easier to customise the relationship.
Issue was brought up in #450
> [FEAT] Make Auditable/User relation more flexible

- src/Resolvers/UrlResolver.php
Prevents trailing question marks in Audit URLs. Fixes #471.
> Update UrlResolver to use Request::fullUrl()

- .gitignore
- config/audit.php
- src/Auditable.php
This allows disabling auditing globally using the config:
`'enabled' => env('AUDITING_ENABLED', true),`
It "fixes" https://github.com/owen-it/laravel-auditing/issues/435
I decided to implement it because I'm using a custom driver that sends notifications through AWS SNS, so I need to disable auditing locally.
> Added audit.enabled config.

- src/Console/InstallCommand.php
to remove the seemingly last occurence of the now obsolete str_* methods and with that the dependency on laravel/helpers package
as mentioned at #545
> Substitute str_replace_last with the respective Str helper

- .gitignore
- composer.json
Remove none need package, then add `.phpunit.result.cache` to `.gitignore`
> Remove none need package

- .scrutinizer.yml
- .travis.yml
- README.md
- composer.json
- src/Auditor.php
This PR aims to support the release of Laravel 8
The minimum php version required has been bumped to 7.3.
References to `app` has been changed to `container` in `Auditor.php`
Readme has been updated however it might not be 100% correct, let me know if I messed it up 😄  
travis php version changed to 7.3
scrutinizer php version changed to 7.3
Addresses issue #606
> Laravel 8 Compatibility - includes php version bump, change usage of deprecated $app, updated readme and travis/scrutinizer config updated

- .scrutinizer.yml
- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- phpunit.xml
Had to drop Illuminate 5.8 support as it does not support PHP 8:
https://github.com/laravel/laravel/blob/5.8/composer.json#L11
Also, even though the tests run without problems on php 8, it looks like scrutinizer is failing to fetch php 8.0. We may need to wait for them to fix it.
```
https://secure.php.net/distributions/php-8.tar.bz2
https://secure.php.net/distributions/php-8.0.0.tar.bz2
```
- Fixes #623
> Add PHP 8.0 support

- .styleci.yml
- src/Auditable.php
Sometimes we need to disable audits even running on console (for example on tests) but without this to get this behaviour we have to set the config running on console to false.
With this fix, disable audits will be disabled on all environments.
> Fix: Disable audits with config even if is running on console

- src/AuditingServiceProvider.php
> Dont publish migration if migration exists

- config/audit.php
- src/Contracts/UserResolver.php
- src/Resolvers/UserResolver.php
Laravel Auth changed and it would be nice to change default guard. New laravel installs throws an exception from the previous default api guard, but to avoid breaking backwards we could skip unavailable guards and set a sensible default
> Default user guard

- src/Auditable.php
As per this issue — https://github.com/owen-it/laravel-auditing/issues/698
> `$auditEvent` from protected to public to make AuditCustom possible

- src/Auditable.php
Consider we have an eloquent **Post** model and a `BelongsToMany` relationship with **Tags**. In **Post** `booted` method, we handle the detaching of **Tags** like:
```php
protected static function booted()
{
static::deleting(function (self $post) {
$post->auditDetach('posts');
});
}
```
When deleting a post, we are detaching the tags first. This creates an audit with the event "detach". Then, the Post is deleted and a "delete" audit event is stored. But the audit values are not correct; they are actually the `old_values` and `new_values` of the detach event.
Adding `$post->isCustomEvent = false;` after the `$post->auditDetach()` fixes the issue in userland. So this PR sets the `$isCustomEvent` property to `false` after the auditAttach, auditDetach & auditSync methods.
> Reset isCustomEvent flag after attach/detach/sync events

- config/audit.php
- src/Auditable.php
- src/Auditor.php
- tests/Functional/AuditingTest.php
We found that often we are storing models to make minor changes but some relationships are not changed. If we do a `auditSync` call, we will get an audit even if the relationship was not affected. 
This PR adds a method `auditSyncIfChanged` which will abort the audit when it finds the relationship sync() call had 0 attached, updated or detached items.
> Add option to skip auditSync when sync has no changes

- src/Auditable.php
When users do not upgrade config according to documentation, audit fails with exception
We could allow for fallback to v12 config and set a deprecation notice instead of throwing exception.
relates to issue #694
> Deprecated config causes errors

- database/migrations/audits.stub
On migration use setted morph prefix from config, same as other places
https://github.com/owen-it/laravel-auditing/blob/2317a5ed72f0c4256b1c274d3e6ef53db5d0598c/src/Auditable.php#L320
https://github.com/owen-it/laravel-auditing/blob/2317a5ed72f0c4256b1c274d3e6ef53db5d0598c/src/Auditable.php#L332-L333
> User morph prefix from config on migration

- database/migrations/audits.stub
If the user specifies a different db connection for the audits table in their config file than the one used by the rest of the app, the default migration would not take this into account. Personally I use a different database for my audits table so I needed to modify the migration like I've done in this PR.
> Use configured db connection in default migration

- src/Auditable.php
This will fix attributes with enum values from being automatically excluded.
For details look at [this](https://github.com/owen-it/laravel-auditing/issues/722) issue.
> Fix attributes with enums being excluded from audit

- src/AuditingEventServiceProvider.php
Closes #728
Another option could be creating a especific event service provider only for lumen, like `AuditingLumenEventServiceProvider::class`
```php
// AuditingServiceProvider.php
public function register()
{
/////
if ($this->app instanceof \Illuminate\Foundation\Application) {
$this->app->register(AuditingEventServiceProvider::class);
} else {
$this->app->register(AuditingLumenEventServiceProvider::class);
}
/////
```
> Restore Lumen support

- src/Auditable.php
Deprecation not means break old functionality
https://en.wikipedia.org/wiki/Deprecation
>Typically, deprecated materials are not completely removed to ensure legacy compatibility or back up practice ...
>It can also imply that a feature, design, or practice will be removed or discontinued entirely in the future.
Same logic from `UserResolver`: (it get the value from old deprected config)
https://github.com/owen-it/laravel-auditing/blob/240b29a1e6c40c02ed1fb9b4c01ef94d6d4ff7c0/src/Auditable.php#L360-L366
> Fix old resolvers config deprecation

- tests/Unit/AuditTest.php
It is better to test using arrays instead of texts, because that way it would show only the value that is not correct instead of all the text, 
besides that in windows there is an error crlf
better readability
> Fix test on windows

- src/Audit.php
When I rename the fields "created_at" and "updated_at" it throws an error when using the getModified() method.
It throws the following error:
"IlluminateDatabaseEloquentModel::serializeDate():
> Bug when "created_at" and "updated_at" fields are named differently

- src/Resolvers/DumpResolver.php
https://github.com/owen-it/laravel-auditing/blob/75b33ec9b4345e4539d94d6c28233b34c5d2730f/config/audit.php#L44-L48
If we don't want any data
```php
'resolvers' => [ 
'ip_address' => OwenIt\Auditing\Resolvers\DumpResolver::class, 
'user_agent' => OwenIt\Auditing\Resolvers\DumpResolver::class, 
'url'        => OwenIt\Auditing\Resolvers\DumpResolver::class, 
], 
```
> Add DumpResolver for empty values when is needed

- database/migrations/audits.stub
- tests/AuditingTestCase.php
- tests/Functional/AuditingTest.php
- tests/database/migrations/0000_00_00_000001_create_audits_test_table.php
On config we have `audit.drivers.database.table` but on migration it is never called, this PR fix migration
- Clean trailing spaces on migration
- Use table name from config `$table = config('audit.drivers.database.table', 'audits');`
- Use a custom table name on tests, this test that functionality
- Test original [audits migration](https://github.com/owen-it/laravel-auditing/blob/master/database/migrations/audits.stub) instead of [duplicate it](https://github.com/owen-it/laravel-auditing/blob/v13.1.0/tests/database/migrations/0000_00_00_000001_create_audits_test_table.php)
https://github.com/owen-it/laravel-auditing/blob/75b33ec9b4345e4539d94d6c28233b34c5d2730f/config/audit.php#L152-L157
**THIS PR DON'T BREAK PREVIOUS MIGRATIONS**
> Custom table name from config

- src/Contracts/UserResolver.php
The UserResolver demanded a trait as a return type, which should have been the Authenticatable Contract. This is most likely an auto completion error.
Found while using PhpStan level 9 locally.
> (fix): UserResolver authenticatable import

- src/Auditable.php
- tests/Functional/AuditingTest.php
- tests/Unit/AuditableTest.php
The `Auditable::bootAuditable()` trait loader on the model works only once, at the very first initialization of the class. Thus, at the moment, if auditing is disabled on the model during initialization, an observer will not be booted on the model, and a further call to `Model::enableAudit()` will not change anything - there is no observer, no events are registered.
The `itDisablesAndEnablesAuditingBackAgain` test skipped this behavior because the model was first initialized before auditing was disabled.
I suggest init observer on the model, regardless of the `$auditingDisabled` flag. I made the appropriate changes, and the `itDisablesAndEnablesAuditingBackAgainViaFacade` test, where auditing is disabled before initialization.
> Fix disable auditing before model initialization

- src/Contracts/Auditable.php
``` 
Class OwenIt\Auditing\Contracts\OwenIt\Auditing\Models\Audit was not found while trying to analyse it - discovering symbols is probably not configured properly.  
💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                  
```
> fixing phpstan namespace issues

- src/Contracts/Auditable.php
Fixes an phpstan (Larastan) internal error which we only started getting after #798
> Use FQN instead of alias to fix phpstan internal error

- src/Auditor.php
This error is returned if return type void is not provided using  PHP Version > 8.1.19:
Declaration of OwenIt\Auditing\Auditor::execute(OwenIt\Auditing\Contracts\Auditable $model) must be compatible with OwenIt\Auditing\Contracts\Auditor::execute(OwenIt\Auditing\Contracts\Auditable $model): void
> Update return value of Auditor->execute so that it works for PHP Version 8.1.19

- src/Auditable.php
An empty collection, when calling `->toArray()` will return `[]`, which makes the need to load the results of the relationship twice unnecessary.
> Don't need to execute these calls multiple times

- src/Concerns/GathersDataToAudit.php
I'm testing V14 and i'm getting
`preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated`
With this PR everything works again
> [V14] Fix preg_match() Passing null to parameter 2

- src/Auditable.php
i wanted to select which columns are stored to DB when using `auditAttach()` method and found this `$columns` attribute which was not used anywhere, i think this could be the right place.
> allow selecting columns to be saved when using auditAttach() method

- src/Auditable.php
in addition to my recent PR https://github.com/owen-it/laravel-auditing/pull/844/ i've just realized i missed the rest of the methods 🤦‍♂️ so here is the rest
> allow selecting columns to be saved when using auditDetach(), auditSync() and auditSyncWithoutDetaching()

- .github/workflows/run-tests.yml
- phpunit.xml
- src/Resolvers/UrlResolver.php
- tests/AuditingTestCase.php
- tests/Unit/AuditTest.php
- tests/Unit/AuditableTest.php
Hello,
I've had ambiguous audits in the past where we couldn't determinate from which of our scheduled command these modifications were coming from because everything is "console", so the debugging experience were not ideal.
To improve the situation I implemented a custom way to retrieve the proper command line used while generating the audit, this works great for us. 
So I decided to contribute it.
*Note*: Since the url metadata is now non deterministic in tests because of various possible ways to run the tests (arguments, options, paths, etc.), I've decided to expose the command line resolving logic to make use of it in tests that are not meant to test this feature specifically. 
And then introduce a test that is meant to run with a specific command line and thus expect a deterministic …
> Make UrlResolver resolve the proper command line used instead of "console"

- src/Audit.php
- tests/Casts/Money.php
- tests/Models/Article.php
- tests/Models/Money.php
- tests/Unit/AuditTest.php
- tests/database/migrations/0000_00_00_000003_create_articles_test_table.php
"[getFormattedValue](https://github.com/owen-it/laravel-auditing/blob/master/src/Audit.php#L122-L148)" method is calling laravel will get the value from the classCastCache property. So old and new values are the same. This PR unset the classCastCache for given key so old value is not retrieve from cache.
Fix issue: #588
> Unset classCastCache for given key

- src/Audit.php
- tests/Functional/AuditingTest.php
- tests/Models/Article.php
- tests/Unit/AuditTest.php
- tests/Unit/AuditableTest.php
This pull request addresses the issue of the Audit functionality in the Laravel framework failing to include attribute accessors  during the formatting process. 
To solve this issue, I have made modifications to the Audit functionality. The changes now include attribute accessors  when formatting the data. This ensures that any custom formatting defined through attribute accessors is properly considered.
Related Issue #828 
Checklist
> Include Attribute Mutator on Audit Formatting

- src/AuditableObserver.php
The previous PR #881 made the default behavior opt-out, while I think we actually want it to be opt-in to avoid breaking changes.
For some more context, I am updating composer packages and our test cases were failing that were concerned with auditing. After some digging, I realized I had to copy over the updates to config/audit.php and ensure that we had `'audit.queue.enabled'` set to `false`.
With the change proposed in this PR, there's no need to copy over the configuration (which isn't always obvious), it will just work exactly as it did previously without updating the configuration.
> Make queued auditing opt-in

- config/audit.php
- src/Auditable.php
- tests/Unit/AuditableTest.php
- tests/database/migrations/0000_00_00_000003_create_articles_test_table.php
In projects utilizing MongoDB as the database, data is commonly stored in the form of arrays and objects. However, non-scalar values are not allowed to be recorded in this packages. 
Therefore, I have added a new config to provide users with the option to audit array values.
Issue: #596
> Add config to allow records array values

- README.md
The official documentation "repository" link is still leading to the old archived repo https://github.com/owen-it/laravel-auditing-doc/. Update to the currently-maintained https://github.com/owen-it/laravel-auditing.com/.
> Fix "repository" link in README.md

- src/Auditable.php
- tests/Functional/AuditingTest.php
- tests/Unit/AuditableTest.php
Similar to Laravel's `Model::withoutEvents()` method, allow running Eloquent queries on a given model class inside a callback:
```php
User::withoutAuditing(function () use ($user, $inputs, $additional) {
// no audit
$user->update($inputs);
// this _will_ be audited if the Profile class is Auditable
$user->profile()->updateOrCreate([], $additional);
});
```
Only the `{class}::withoutAuditing()` class will have auditing disabled, so additional model classes need their own call. e.g.,
```php
User::withoutAuditing(fn () => $user->update($inputs));
Profile::withoutAuditing(fn () => $user->profile()->updateOrCreate([], $additional));
```
---
1. It's wrapped in `try` / `finally` to handle restoring auditing after Eloquent possibly throws `QueryException`.
2. If auditing is already disabled, that …
> Add `withoutAuditing()` callback method to temporarily disable auditing for one class

- src/Auditable.php
- tests/Functional/AuditingTest.php
https://github.com/owen-it/laravel-auditing/pull/921#issuecomment-2130003148
>also `syncWithPivotValues` is missing
https://laravel.com/docs/9.x/eloquent-relationships#syncing-associations
[Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#syncWithPivotValues](https://github.com/laravel/framework/blob/7c2d7c0165582f3dd29052aa7589e4395d0366e5/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L133-L143)
> Added `auditSyncWithPivotValues` method

- src/Drivers/Database.php
- tests/Functional/AuditingTest.php
> Fix database prune, offset not working on some dbs

- tests/Functional/AuditingTest.php
- tests/Unit/AuditTest.php
- tests/Unit/AuditableTest.php
I broke the tests figuring out how v14 works and it would have been easier to figure out what was happening if the tests explicitly told me that there were no audits.
Removed a few docblocks and fixed a few other assertions.
> 🚨 first is nullable

- src/AuditableObserver.php
- src/Contracts/Auditor.php
Returning from a void function caused a big error at one point during my tests, presumably not a problem currently but may well be soon.
Also cleaned up the contract but left the void as sort of optional in case someone out there is returning from it.
> 🐛 void function does not return

- src/Events/DispatchAudit.php
When I tried to add the array types for phpstan, php linting pointed out this function must return void and not array. Also there was a missing space I spotted.
I'm presuming this return has just been unused all this time but I can't say I have used unserialize for a long time.
> 🐛 unserialize must be void

- src/Audit.php
- src/Console/InstallCommand.php
Also from phpstan, there are some places where the code ignores potential null and false returns.
In v14, past you went with another level of ternary, I adapted it into more intentional if statements.
> ♻️ deal with null and false returns

- src/Audit.php
- src/AuditableObserver.php
- src/Auditor.php
- src/Console/InstallCommand.php
- src/Contracts/AttributeRedactor.php
- src/Contracts/Audit.php
- src/Contracts/AuditDriver.php
- src/Contracts/Auditable.php
- src/Events/AuditCustom.php
- src/Events/Audited.php
- src/Events/Auditing.php
- src/Events/DispatchAudit.php
- src/Events/DispatchingAudit.php
- src/Exceptions/AuditableTransitionException.php
- src/Listeners/ProcessDispatchAudit.php
- src/Listeners/RecordCustomAudit.php
- src/Models/Audit.php
- src/Resolvers/UrlResolver.php
- src/Resolvers/UserAgentResolver.php
A first pass of doc types, referencing the v14 branch as well as phpstan level 8, removing duplicated types and adding missing types.
I'm hoping this is basic enough to not cause any issues.
> ♻️ doc types first pass

- src/Resolvers/UserAgentResolver.php
`Request::header` could possibly return null. Fix by adding default empty string return.
> Fix null return in UserAgentResolver

- src/Audit.php
- src/Drivers/Database.php
- src/Resolvers/UrlResolver.php
- tests/Functional/AuditingTest.php
https://github.com/owen-it/laravel-auditing/pull/933/files
In the old version (`->get()->slice($threshold)->pluck('id')`) Memory performance was failing, since with `get()` all the data was brought as eloquent models
Now (`->pluck($keyName)->all()`) `pluck/all` is done directly, which would only use an int array
`whereIn` was replaced by `whereIntegerInRaw`(avoid too many Placeholders issue)
The same solution works on older Laravel versions, if merged it would also be released in v13: https://github.com/owen-it/laravel-auditing/actions/runs/14862464393/job/41730649233
UPDATE: `whereIntegerInRaw` would cause problems when the key is a string, like UUID?
> [v14] Phpstan fixes

- src/Models/Audit.php
I've been working on implementing some functionality for managing audit history in Filament, and I noticed that PHPStan gives an error for `created_at` and `updated_at` being undefined properties.
This PR type-hints them alongside some of the other model properties to resolve this.
> Typehint `created_at` and `updated_at` values for phpstan

- src/Models/Audit.php
EDIT: imported Carbon, apparently I missed that last time. Sorry 😬 
Hi, Another addition to the Audit docblock to help with PHPStan type hinting.
This one is to add the `auditable_type` and `auditable_id` columns used for the `auditable` relation so they can be selcted, plucked, etc. The reason for this is an example below:
```php
Audit::query()->distinct()->pluck('auditable_type');
```
In PHPStan levels 7 and above, this gives the following error:
```
------ ----------------------------------------------------------------------------- 
Line   Filament/AuditResource.php                                                   
------ ----------------------------------------------------------------------------- 
241    Parameter #1 $column of method …
```
> Add `auditable_type` and `auditable_id` properties to Audit Model
